services:
  dynamodb-local:
    image: amazon/dynamodb-local:latest
    container_name: nexus-dynamodb
    # Simpel aja, tanpa -dbPath supaya gak kena error sqlite permission
    command: "-jar DynamoDBLocal.jar -sharedDb"
    ports:
      - "8000:8000"

  dynamodb-admin:
    image: aaronshaf/dynamodb-admin
    container_name: nexus-admin
    depends_on:
      - dynamodb-local
    environment:
      # Pakai nama container DynamoDB sebagai host
      DYNAMO_ENDPOINT: "http://nexus-dynamodb:8000"
      AWS_REGION: "ap-southeast-1"
      AWS_ACCESS_KEY_ID: "local"
      AWS_SECRET_ACCESS_KEY: "local"
    ports:
      - "8001:8001"

  redis-local:
    image: redis:alpine
    container_name: nexus-redis
    command: redis-server --requirepass devpass --appendonly yes
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  redis_data:
